

name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every 24 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Bilal-khan980
          outputs: |
            ./output/github-contribution-grid-snake.svg
      - name: Push snake
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '🐍 Update contribution snake'
